var titleReg = /^[A-Za-z0-9_!?,.';'#-: ]{1,200}$/;
var descriptionReg = /^[A-Za-z0-9_<>,.!?/\n="';&-: ]{3,1000}$/;
var numChoicesReg =  /^[2-9]{1}$/;
var emailReg = /^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i ;
var ipfs;
var web3;
var distrivoteContractABI = [{"constant":true,"inputs":[{"name":"pollHash","type":"string"}],"name":"getPoll","outputs":[{"name":"","type":"address"},{"name":"","type":"address"},{"name":"","type":"uint256"},{"name":"","type":"uint256"},{"name":"","type":"bool"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"pollHash","type":"string"},{"name":"account","type":"address"}],"name":"getAddressVote","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"pollHash","type":"string"}],"name":"getVotersLength","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"pollHash","type":"string"},{"name":"paused","type":"bool"}],"name":"pausePoll","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"pollHash","type":"string"},{"name":"limit","type":"uint256"},{"name":"offset","type":"uint256"}],"name":"getVoters","outputs":[{"name":"_voters","type":"address[]"},{"name":"_choiceIds","type":"uint256[]"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"owner","outputs":[{"name":"","type":"address"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"newWei","type":"uint256"}],"name":"setMinimumTransactionWei","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"minTransactionWei","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"weiAmount","type":"uint256"}],"name":"transferWei","outputs":[],"payable":false,"type":"function"},{"constant":false,"inputs":[],"name":"transferAllWei","outputs":[],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"newOwner","type":"address"}],"name":"transferOwnership","outputs":[],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"pollHash","type":"string"},{"name":"contractAddress","type":"address"},{"name":"choicesCount","type":"uint256"}],"name":"createPoll","outputs":[],"payable":true,"type":"function"},{"constant":false,"inputs":[{"name":"pollHash","type":"string"},{"name":"choiceId","type":"uint256"}],"name":"carbonvote","outputs":[],"payable":false,"type":"function"},{"anonymous":false,"inputs":[{"indexed":false,"name":"pollHash","type":"string"}],"name":"onPollCreated","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"pollHash","type":"string"}],"name":"onPollPaused","type":"event"}];
var erc20ABI = [{"constant":false,"inputs":[{"name":"_spender","type":"address"},{"name":"_value","type":"uint256"}],"name":"approve","outputs":[{"name":"success","type":"bool"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"totalSupply","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_from","type":"address"},{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transferFrom","outputs":[{"name":"success","type":"bool"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"}],"name":"balanceOf","outputs":[{"name":"balance","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transfer","outputs":[{"name":"success","type":"bool"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"},{"name":"_spender","type":"address"}],"name":"allowance","outputs":[{"name":"remaining","type":"uint256"}],"payable":false,"type":"function"},{"anonymous":false,"inputs":[{"indexed":true,"name":"_from","type":"address"},{"indexed":true,"name":"_to","type":"address"},{"indexed":false,"name":"_value","type":"uint256"}],"name":"Transfer","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"_owner","type":"address"},{"indexed":true,"name":"_spender","type":"address"},{"indexed":false,"name":"_value","type":"uint256"}],"name":"Approval","type":"event"}];

var distrivoteContractAddress = '0xAf0a6543d318A919E48F0AF0Cd757aF0cB2C8bc7'; // Ropsten Address: 0xd0AA4e0ba1d49342c10877c97d4970CB68451c73
var account;
var tokenContractAddress;
var erc20Contract;
var erc20Symbol = "tokens";
var contractHash;
var distrivoteContract;
var limit=100;
var minEthTransaction = 0.01;

var votersLimit = 200;
var ipfsHost="ipfs.infura.io";
var ipfsPort = 5001;
var ipfsProtocol = "https";
